name: train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.SOME_SECRET }}
        run: |
          pip3 install --upgrade pip
          pip install -r requirements.txt
          dvc remote modify storage url gdrive://root/1R6YWU6OBQL_c3wrMcsV1-keyuLE8eqtc
          dvc remote modify storage --local gdrive_use_service_account true
          dvc pull
          dvc repro
          git fetch

          cml asset publish generated_script.txt --md >> report.md

          cml-send-comment report.md