name: train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.SOME_SECRET }}
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
        run: |
          pip3 install --upgrade pip
          pip install -r requirements.txt
          dvc pull
          dvc repro
          git fetch

          cml asset publish generated_script.txt --md >> report.md

          cml-send-comment report.md